import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

const adapter = new PrismaBetterSqlite3({
  url: "file:./prisma/dev.db",
});
const prisma = new PrismaClient({ adapter });

const cars = [
  // === BUDGET HATCHBACKS (₹5-8L) ===
  {
    make: "Maruti Suzuki",
    model: "Swift",
    variant: "VXi",
    year: 2024,
    priceLakh: 6.49,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    mileageKmpl: 22.56,
    engineCc: 1197,
    seats: 5,
    safetyRating: 4,
    features: JSON.stringify(["dual_airbags", "abs", "rear_parking_sensors", "smartplay_infotainment", "steering_mounted_controls"]),
    pros: JSON.stringify(["Best-in-class mileage", "Peppy engine", "Wide service network", "Good resale value"]),
    cons: JSON.stringify(["Firm ride quality", "Smaller boot space", "No sunroof in base variants"]),
    summary: "India's best-selling premium hatchback with a perfect balance of performance and fuel efficiency.",
  },
  {
    make: "Hyundai",
    model: "i20",
    variant: "Sportz",
    year: 2024,
    priceLakh: 7.85,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    mileageKmpl: 20.35,
    engineCc: 1197,
    seats: 5,
    safetyRating: 4,
    features: JSON.stringify(["sunroof", "wireless_charging", "apple_carplay", "android_auto", "connected_car_tech", "air_purifier"]),
    pros: JSON.stringify(["Feature-loaded cabin", "Premium interior quality", "Smooth ride", "Spacious rear seat"]),
    cons: JSON.stringify(["Slightly expensive for segment", "Turbo variant pricey", "Average boot space"]),
    summary: "The most feature-rich premium hatchback in India with segment-first connected car technology.",
  },
  {
    make: "Tata",
    model: "Altroz",
    variant: "XZ+",
    year: 2024,
    priceLakh: 7.49,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    mileageKmpl: 22.07,
    engineCc: 1199,
    seats: 5,
    safetyRating: 5,
    features: JSON.stringify(["projector_headlamps", "7inch_touchscreen", "apple_carplay", "android_auto", "cruise_control", "auto_headlamps"]),
    pros: JSON.stringify(["5-star safety rating", "Solid build quality", "Spacious cabin", "Good ride quality"]),
    cons: JSON.stringify(["Engine feels underpowered", "No automatic in petrol", "Average infotainment"]),
    summary: "India's safest hatchback with a 5-star Global NCAP rating and solid build quality.",
  },
  {
    make: "Maruti Suzuki",
    model: "Baleno",
    variant: "Delta",
    year: 2024,
    priceLakh: 6.61,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    mileageKmpl: 22.35,
    engineCc: 1197,
    seats: 5,
    safetyRating: 3,
    features: JSON.stringify(["smartplay_pro", "heads_up_display", "cruise_control", "auto_ac", "push_button_start"]),
    pros: JSON.stringify(["Spacious cabin", "Great mileage", "Smooth CVT option", "Heads-up display"]),
    cons: JSON.stringify(["Average safety rating", "Thin sheet metal feel", "Basic suspension"]),
    summary: "A spacious and fuel-efficient premium hatchback with segment-first heads-up display.",
  },
  {
    make: "Tata",
    model: "Tiago",
    variant: "XZ+",
    year: 2024,
    priceLakh: 5.65,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    mileageKmpl: 23.84,
    engineCc: 1199,
    seats: 5,
    safetyRating: 4,
    features: JSON.stringify(["dual_airbags", "abs", "harman_audio", "apple_carplay", "android_auto"]),
    pros: JSON.stringify(["Most affordable safe car", "Excellent mileage", "Peppy engine", "Good build quality"]),
    cons: JSON.stringify(["Compact rear seat", "Basic interior", "Road noise at highway speeds"]),
    summary: "The most affordable 4-star rated car in India with excellent fuel economy.",
  },
  {
    make: "Maruti Suzuki",
    model: "WagonR",
    variant: "ZXi+",
    year: 2024,
    priceLakh: 5.95,
    fuelType: "CNG",
    transmission: "Manual",
    bodyType: "Hatchback",
    mileageKmpl: 34.05,
    engineCc: 1197,
    seats: 5,
    safetyRating: 2,
    features: JSON.stringify(["smartplay_studio", "steering_mounted_controls", "auto_ac", "electrically_adjustable_orvm"]),
    pros: JSON.stringify(["Outstanding CNG mileage", "Tallboy design with great headroom", "Low running cost", "Reliable engine"]),
    cons: JSON.stringify(["Poor safety rating", "Basic cabin quality", "Boot space reduced with CNG tank"]),
    summary: "India's best-selling CNG car with unbeatable running costs and practical tallboy design.",
  },

  // === MID-RANGE SEDANS (₹8-15L) ===
  {
    make: "Hyundai",
    model: "Verna",
    variant: "SX",
    year: 2024,
    priceLakh: 12.49,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    mileageKmpl: 18.6,
    engineCc: 1497,
    seats: 5,
    safetyRating: 5,
    features: JSON.stringify(["sunroof", "ventilated_seats", "wireless_charging", "bose_audio", "adas", "connected_car_tech", "6_airbags"]),
    pros: JSON.stringify(["ADAS safety features", "Premium cabin", "Ventilated seats", "Powerful turbo engine"]),
    cons: JSON.stringify(["Expensive top variants", "Firm low-speed ride", "Turbo DCT can be jerky in traffic"]),
    summary: "A tech-loaded sedan with Level 2 ADAS and premium features rivaling cars twice its price.",
  },
  {
    make: "Honda",
    model: "City",
    variant: "ZX",
    year: 2024,
    priceLakh: 13.35,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    mileageKmpl: 18.4,
    engineCc: 1498,
    seats: 5,
    safetyRating: 4,
    features: JSON.stringify(["sunroof", "lane_watch_camera", "honda_connect", "alexa_built_in", "6_airbags", "cruise_control"]),
    pros: JSON.stringify(["Refined engine", "Spacious rear seat", "Excellent ride quality", "Honda reliability"]),
    cons: JSON.stringify(["Missing ADAS", "Interior design feels dated", "CVT lacks sportiness"]),
    summary: "The quintessential sedan with unmatched rear-seat comfort and Honda's legendary reliability.",
  },
  {
    make: "Maruti Suzuki",
    model: "Ciaz",
    variant: "Alpha",
    year: 2024,
    priceLakh: 9.85,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    mileageKmpl: 20.04,
    engineCc: 1462,
    seats: 5,
    safetyRating: 3,
    features: JSON.stringify(["smartplay_pro", "cruise_control", "rear_ac_vents", "push_button_start", "auto_headlamps"]),
    pros: JSON.stringify(["Best mileage in sedans", "Spacious cabin", "Affordable maintenance", "Smooth AT"]),
    cons: JSON.stringify(["Dated design", "Lacks features vs rivals", "Average safety"]),
    summary: "A no-fuss sedan that prioritizes fuel efficiency and low ownership costs.",
  },

  // === MID-RANGE SUVs (₹10-18L) ===
  {
    make: "Hyundai",
    model: "Creta",
    variant: "SX(O)",
    year: 2024,
    priceLakh: 15.98,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 17.0,
    engineCc: 1497,
    seats: 5,
    safetyRating: 5,
    features: JSON.stringify(["panoramic_sunroof", "ventilated_seats", "adas", "bose_audio", "360_camera", "wireless_charging", "air_purifier"]),
    pros: JSON.stringify(["Feature-loaded like a luxury car", "Strong turbo engine", "5-star safety", "Great resale"]),
    cons: JSON.stringify(["Premium pricing", "Firm ride on bad roads", "Turbo DCT jerky in traffic"]),
    summary: "India's best-selling SUV loaded with segment-first features and Level 2 ADAS.",
  },
  {
    make: "Kia",
    model: "Seltos",
    variant: "HTX+",
    year: 2024,
    priceLakh: 14.79,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 20.7,
    engineCc: 1493,
    seats: 5,
    safetyRating: 5,
    features: JSON.stringify(["sunroof", "ventilated_seats", "air_purifier", "bose_audio", "360_camera", "connected_car_tech"]),
    pros: JSON.stringify(["Excellent diesel engine", "Feature-rich cabin", "Good highway mileage", "Sharp styling"]),
    cons: JSON.stringify(["Road noise at speed", "Basic rear AC", "AT diesel can be slow to respond"]),
    summary: "A sharp-looking SUV with an efficient diesel engine and comprehensive tech package.",
  },
  {
    make: "Tata",
    model: "Nexon",
    variant: "XZ+(P)",
    year: 2024,
    priceLakh: 11.49,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 17.44,
    engineCc: 1199,
    seats: 5,
    safetyRating: 5,
    features: JSON.stringify(["sunroof", "ventilated_seats", "air_purifier", "wireless_charging", "connected_car_tech", "6_airbags"]),
    pros: JSON.stringify(["5-star NCAP safety", "Solid build quality", "Good ground clearance", "Punchy turbo engine"]),
    cons: JSON.stringify(["Compact boot", "Engine can feel stressed on highway", "AMT not as smooth as DCT"]),
    summary: "India's safest sub-compact SUV with a 5-star safety rating and rugged build.",
  },
  {
    make: "Maruti Suzuki",
    model: "Grand Vitara",
    variant: "Alpha+",
    year: 2024,
    priceLakh: 14.99,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 27.97,
    engineCc: 1490,
    seats: 5,
    safetyRating: 5,
    features: JSON.stringify(["panoramic_sunroof", "heads_up_display", "wireless_charging", "360_camera", "hybrid_system", "cruise_control"]),
    pros: JSON.stringify(["Class-leading mileage with hybrid", "Maruti service network", "Spacious cabin", "5-star safety"]),
    cons: JSON.stringify(["CVT lacks punch", "Boot space average", "Road presence below rivals"]),
    summary: "A strong hybrid SUV offering exceptional mileage without compromising on features or safety.",
  },
  {
    make: "Mahindra",
    model: "XUV700",
    variant: "AX7",
    year: 2024,
    priceLakh: 17.49,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 16.0,
    engineCc: 2184,
    seats: 7,
    safetyRating: 5,
    features: JSON.stringify(["adas", "panoramic_sunroof", "sony_3d_audio", "wireless_charging", "flush_door_handles", "dual_zone_ac"]),
    pros: JSON.stringify(["Powerful diesel engine", "7-seat configuration", "5-star safety + ADAS", "Excellent value"]),
    cons: JSON.stringify(["Long waiting periods", "Quality inconsistencies reported", "Third-row cramped"]),
    summary: "A feature-packed 7-seater SUV that punches way above its price with ADAS and premium audio.",
  },
  {
    make: "Tata",
    model: "Harrier",
    variant: "Fearless+",
    year: 2024,
    priceLakh: 18.49,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 16.8,
    engineCc: 1956,
    seats: 5,
    safetyRating: 5,
    features: JSON.stringify(["panoramic_sunroof", "jbl_audio", "adas", "ventilated_seats", "360_camera", "air_purifier"]),
    pros: JSON.stringify(["Stunning road presence", "Powerful diesel engine", "5-star safety + ADAS", "Premium cabin"]),
    cons: JSON.stringify(["Only diesel option", "No petrol variant", "Stiff suspension"]),
    summary: "A head-turning SUV with Land Rover-derived platform and top-notch safety credentials.",
  },
  {
    make: "MG",
    model: "Hector",
    variant: "Sharp Pro",
    year: 2024,
    priceLakh: 16.49,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 14.8,
    engineCc: 1451,
    seats: 5,
    safetyRating: 4,
    features: JSON.stringify(["panoramic_sunroof", "14inch_touchscreen", "adas", "wireless_charging", "ventilated_seats", "powered_tailgate"]),
    pros: JSON.stringify(["Biggest touchscreen in segment", "ADAS at competitive price", "Spacious cabin", "Good ride quality"]),
    cons: JSON.stringify(["Average petrol mileage", "Dated exterior design", "MG service network limited"]),
    summary: "The tech-savvy SUV with a massive 14-inch touchscreen and comprehensive ADAS suite.",
  },
  {
    make: "Kia",
    model: "Sonet",
    variant: "HTX+",
    year: 2024,
    priceLakh: 10.79,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 24.1,
    engineCc: 1493,
    seats: 5,
    safetyRating: 3,
    features: JSON.stringify(["sunroof", "ventilated_seats", "bose_audio", "air_purifier", "connected_car_tech", "rear_ac_vents"]),
    pros: JSON.stringify(["Excellent diesel mileage", "Feature-packed cabin", "Fun iMT gearbox", "Compact city-friendly size"]),
    cons: JSON.stringify(["Average safety rating", "Cramped rear seat", "Firm ride quality"]),
    summary: "A compact SUV that packs big-car features in a city-friendly package.",
  },
  {
    make: "Maruti Suzuki",
    model: "Brezza",
    variant: "ZXi+",
    year: 2024,
    priceLakh: 10.99,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 19.8,
    engineCc: 1462,
    seats: 5,
    safetyRating: 4,
    features: JSON.stringify(["sunroof", "heads_up_display", "wireless_charging", "cruise_control", "auto_ac", "push_button_start"]),
    pros: JSON.stringify(["Low maintenance costs", "Wide service network", "Good mileage", "Reliable engine"]),
    cons: JSON.stringify(["Engine lacks punch", "Interior quality average", "No diesel option"]),
    summary: "India's most practical sub-compact SUV with unbeatable service network and low running costs.",
  },

  // === PREMIUM SUVs (₹20-35L) ===
  {
    make: "Hyundai",
    model: "Tucson",
    variant: "Signature",
    year: 2024,
    priceLakh: 29.02,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 18.4,
    engineCc: 1997,
    seats: 5,
    safetyRating: 5,
    features: JSON.stringify(["panoramic_sunroof", "ventilated_seats", "adas", "bose_audio", "360_camera", "wireless_charging", "powered_tailgate", "air_purifier"]),
    pros: JSON.stringify(["Stunning parametric design", "Loaded with features", "Strong diesel engine", "5-star safety"]),
    cons: JSON.stringify(["Expensive for Hyundai", "Firm ride quality", "Limited service network for premium segment"]),
    summary: "A premium SUV with jaw-dropping design and features that rival European luxury SUVs.",
  },
  {
    make: "Tata",
    model: "Safari",
    variant: "Accomplished+",
    year: 2024,
    priceLakh: 22.99,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 14.5,
    engineCc: 1956,
    seats: 7,
    safetyRating: 5,
    features: JSON.stringify(["panoramic_sunroof", "jbl_audio", "adas", "ventilated_seats", "360_camera", "air_purifier", "wireless_charging"]),
    pros: JSON.stringify(["Iconic brand name", "True 7-seater with usable third row", "5-star safety + ADAS", "Premium cabin"]),
    cons: JSON.stringify(["Diesel only", "Poor mileage", "Heavy and slow in city"]),
    summary: "The legendary Safari reborn as a premium 7-seater with modern safety and luxury features.",
  },
  {
    make: "MG",
    model: "Gloster",
    variant: "Savvy",
    year: 2024,
    priceLakh: 33.98,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 11.95,
    engineCc: 1996,
    seats: 7,
    safetyRating: 5,
    features: JSON.stringify(["adas", "panoramic_sunroof", "pm2_5_filter", "12_3inch_touchscreen", "heated_seats", "powered_tailgate", "4wd"]),
    pros: JSON.stringify(["Full-size SUV presence", "4WD capability", "ADAS suite", "Massive cabin space"]),
    cons: JSON.stringify(["Very poor mileage", "Limited MG service network", "Expensive to maintain"]),
    summary: "A full-size luxury SUV with genuine 4WD capability and impressive road presence.",
  },
  {
    make: "Toyota",
    model: "Fortuner",
    variant: "Legender",
    year: 2024,
    priceLakh: 34.89,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 10.0,
    engineCc: 2755,
    seats: 7,
    safetyRating: 5,
    features: JSON.stringify(["connected_car_tech", "jbl_audio", "powered_tailgate", "wireless_charging", "cruise_control", "auto_headlamps"]),
    pros: JSON.stringify(["Bulletproof reliability", "Strong 4x4 capability", "Excellent resale value", "Powerful engine"]),
    cons: JSON.stringify(["Very expensive", "Poor city mileage", "Stiff ride quality", "Basic infotainment"]),
    summary: "The undisputed king of rugged SUVs with legendary Toyota reliability and go-anywhere ability.",
  },
  {
    make: "Mahindra",
    model: "Scorpio N",
    variant: "Z8L",
    year: 2024,
    priceLakh: 19.49,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 15.31,
    engineCc: 2184,
    seats: 7,
    safetyRating: 5,
    features: JSON.stringify(["sunroof", "sony_audio", "adas", "wireless_charging", "connected_car_tech", "dual_zone_ac"]),
    pros: JSON.stringify(["Powerful diesel engine", "True body-on-frame SUV", "5-star safety", "Excellent value"]),
    cons: JSON.stringify(["Cramped third row", "Average plastic quality", "Long waiting periods"]),
    summary: "A muscular body-on-frame SUV that offers genuine 5-star safety and a powerful diesel engine at a great price.",
  },

  // === MUVs ===
  {
    make: "Toyota",
    model: "Innova Hycross",
    variant: "ZX(O)",
    year: 2024,
    priceLakh: 24.59,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "MUV",
    mileageKmpl: 21.1,
    engineCc: 1987,
    seats: 7,
    safetyRating: 5,
    features: JSON.stringify(["panoramic_sunroof", "ottoman_seats", "jbl_audio", "wireless_charging", "360_camera", "connected_car_tech"]),
    pros: JSON.stringify(["Outstanding ride comfort", "Hybrid efficiency", "Ottoman second-row seats", "Toyota reliability"]),
    cons: JSON.stringify(["Very expensive top variants", "Long waiting periods", "Third-row access difficult"]),
    summary: "A luxury MPV with hybrid tech, ottoman seats, and unmatched ride comfort for families.",
  },
  {
    make: "Kia",
    model: "Carens",
    variant: "Luxury+",
    year: 2024,
    priceLakh: 14.59,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "MUV",
    mileageKmpl: 21.3,
    engineCc: 1493,
    seats: 7,
    safetyRating: 3,
    features: JSON.stringify(["sunroof", "ventilated_seats", "bose_audio", "air_purifier", "connected_car_tech", "one_touch_tumble_seats"]),
    pros: JSON.stringify(["Best value 7-seater", "Feature-loaded", "Efficient diesel", "Practical cabin layout"]),
    cons: JSON.stringify(["Average safety rating", "Firm ride on bad roads", "Basic third-row space"]),
    summary: "The best-value 7-seater in India with premium features and efficient diesel engine.",
  },
  {
    make: "Maruti Suzuki",
    model: "Ertiga",
    variant: "ZXi+",
    year: 2024,
    priceLakh: 10.49,
    fuelType: "CNG",
    transmission: "Manual",
    bodyType: "MUV",
    mileageKmpl: 26.11,
    engineCc: 1462,
    seats: 7,
    safetyRating: 3,
    features: JSON.stringify(["smartplay_pro", "cruise_control", "auto_ac", "steering_mounted_controls", "rear_ac_vents"]),
    pros: JSON.stringify(["Best CNG mileage in 7-seaters", "Low running costs", "Wide service network", "Practical design"]),
    cons: JSON.stringify(["Basic safety features", "Boot space with CNG tank", "Underpowered on CNG"]),
    summary: "India's most practical family MPV with outstanding CNG efficiency and Maruti reliability.",
  },

  // === EVs ===
  {
    make: "Tata",
    model: "Nexon EV",
    variant: "Max LR Fearless+",
    year: 2024,
    priceLakh: 18.49,
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 0,
    engineCc: 0,
    seats: 5,
    safetyRating: 5,
    features: JSON.stringify(["sunroof", "ventilated_seats", "air_purifier", "connected_car_tech", "wireless_charging", "cruise_control"]),
    pros: JSON.stringify(["465km range (ARAI)", "Fast charging support", "Low running cost", "5-star safety"]),
    cons: JSON.stringify(["Charging infra still developing", "Long road trips need planning", "Higher upfront cost"]),
    summary: "India's best-selling EV with impressive 465km range and 5-star safety rating.",
  },
  {
    make: "MG",
    model: "ZS EV",
    variant: "Exclusive Pro",
    year: 2024,
    priceLakh: 22.88,
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 0,
    engineCc: 0,
    seats: 5,
    safetyRating: 4,
    features: JSON.stringify(["panoramic_sunroof", "adas", "pm2_5_filter", "wireless_charging", "connected_car_tech", "heated_orvm"]),
    pros: JSON.stringify(["461km range", "ADAS equipped", "Premium cabin feel", "Good ride quality"]),
    cons: JSON.stringify(["Limited MG service network", "Expensive", "Boot space average"]),
    summary: "A premium electric SUV with ADAS and long range, ideal for eco-conscious buyers.",
  },
  {
    make: "Hyundai",
    model: "Ioniq 5",
    variant: "Long Range",
    year: 2024,
    priceLakh: 33.97,
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 0,
    engineCc: 0,
    seats: 5,
    safetyRating: 5,
    features: JSON.stringify(["vehicle_to_load", "reclining_seats", "bose_audio", "adas", "heads_up_display", "wireless_charging", "over_the_air_updates"]),
    pros: JSON.stringify(["Ultra-fast 800V charging", "Futuristic design", "Vehicle-to-Load feature", "Spacious lounge-like cabin"]),
    cons: JSON.stringify(["Very expensive", "Limited charging infra for 800V", "Not practical for long Indian road trips"]),
    summary: "A futuristic premium EV with 800V ultra-fast charging and a cabin that feels like a living room.",
  },

  // === ADDITIONAL SPREAD ===
  {
    make: "Volkswagen",
    model: "Taigun",
    variant: "GT Plus",
    year: 2024,
    priceLakh: 15.69,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 18.23,
    engineCc: 1498,
    seats: 5,
    safetyRating: 5,
    features: JSON.stringify(["sunroof", "ventilated_seats", "wireless_charging", "digital_cockpit", "cruise_control", "tire_pressure_monitor"]),
    pros: JSON.stringify(["German build quality", "Fun to drive TSI engine", "5-star safety", "Solid highway stability"]),
    cons: JSON.stringify(["Expensive maintenance", "Limited service network", "No diesel option"]),
    summary: "A driver's SUV with German engineering, offering the best driving dynamics in its segment.",
  },
  {
    make: "Skoda",
    model: "Slavia",
    variant: "Style",
    year: 2024,
    priceLakh: 13.29,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    mileageKmpl: 18.72,
    engineCc: 1498,
    seats: 5,
    safetyRating: 5,
    features: JSON.stringify(["sunroof", "ventilated_seats", "wireless_charging", "digital_cockpit", "cruise_control", "8_speakers"]),
    pros: JSON.stringify(["Best driving sedan in segment", "1.5 TSI is a gem", "Spacious rear seat", "5-star safety"]),
    cons: JSON.stringify(["Skoda service costs", "DSG can be jerky", "Limited service network"]),
    summary: "A driver-focused sedan with a brilliant TSI engine and European build quality.",
  },
  {
    make: "Renault",
    model: "Kiger",
    variant: "RXZ Turbo",
    year: 2024,
    priceLakh: 8.49,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 20.5,
    engineCc: 999,
    seats: 5,
    safetyRating: 3,
    features: JSON.stringify(["wireless_charging", "apple_carplay", "android_auto", "ambient_lighting", "cruise_control", "pm2_5_filter"]),
    pros: JSON.stringify(["Most affordable turbo SUV", "Good mileage", "Stylish design", "Spacious boot"]),
    cons: JSON.stringify(["Average safety", "Renault service quality varies", "Basic interior feel"]),
    summary: "The most affordable turbo-petrol SUV in India with sporty styling and good boot space.",
  },
  {
    make: "Honda",
    model: "Elevate",
    variant: "ZX",
    year: 2024,
    priceLakh: 13.49,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    mileageKmpl: 15.31,
    engineCc: 1498,
    seats: 5,
    safetyRating: 5,
    features: JSON.stringify(["sunroof", "honda_connect", "adas", "wireless_charging", "6_airbags", "lane_keep_assist"]),
    pros: JSON.stringify(["Honda reliability", "ADAS at competitive price", "Spacious cabin", "Good ride quality"]),
    cons: JSON.stringify(["Underpowered for segment", "CVT lacks excitement", "Average boot space"]),
    summary: "Honda's practical SUV offering reliability, ADAS safety, and a spacious cabin at a competitive price.",
  },
];

async function main() {
  console.log("🚗 Seeding CarMatch database...");

  // Clear existing data
  await prisma.car.deleteMany();

  // Seed cars
  for (const car of cars) {
    await prisma.car.create({ data: car });
  }

  console.log(`✅ Seeded ${cars.length} cars successfully!`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
